### ISSUE TITLE
Your bot crosposted a portugese post to an english sub.

### ISSUE THREAD

**Issue by szalony9szymek** [Toldry/RedditAutoCrosspostBot#1]
https://imgur.com/a/C8M2yY5

**Comment by szalony9szymek** [comment]
https://www.reddit.com/r/thanksimcured/comments/kag5rk/stop_being_poor_tudo_resolvido/

**Comment by Toldry** [comment]
Thanks for reporting this issue @szalony9szymek 

After some deliberation, I conclude that the fact that the bot crossposts between different language subreddits to be more of a good thing than a bad thing, as it encourages "cross pollination" between languages, and users who do not understand the language can simply skim over the post and skip it [though the few seconds that might take are admittedly annoying].

Personally when I browse reddit, I'm subscribed to several subreddits whose language I don't understand, to encourge myself to learn and understand other langages; though I'm aware this habit is not shared or common with other redditors.

Instead of closing the issue right away, I'd like to first hear your thoughts on why this might be a more severe issue than I think it is.
