### ISSUE TITLE
bots which will read the title or flair for some specific key words

### ISSUE THREAD

**Issue by rahulashok360** [Toldry/RedditAutoCrosspostBot#22]
Are there any bots which will read the title or flair for some specific key words and then auto crosspost it to a specified sub reddit

**Comment by Toldry** [comment]
I'm not sure I understand the issue, Can you give an example?

**Comment by rahulashok360** [comment]
"It then saves the link to that comment for later processing. After some waiting period (e.g. 3 months), the bot checks the same comment, and if it has accrued enough upvotes, the bot will crosspost the submission that the comment replied to, to the target subreddit."

Ok instead of this, lets say, the bot should read the flair or some specific keyword in the title of a post and then redirect it to a mentioned/ specified sub, not after 3 months, but after, say, half hour or so.

No need of saving the link as comment or looking for upvotes, just directly crossposting to a specified sub.

For example: 

This post's Flair is "Urban Fantasy" in r/KindleBooks https://www.reddit.com/r/KindleBooks/comments/o6dmc5/blood_heir_is_on_sale_for_today/

So the bot should identify the flair and auto crosspost it to the r/UrbanFantasy subreddit 
https://www.reddit.com/r/urbanfantasy/

Am I clear and is that doable?

**Comment by Toldry** [comment]
Oh, yes, this is doable.

However, I think it's better create a separate bot for this specialized use case, rather than adding this functionality onto u/AutoCrosspostBot.

Therefore I am closing this issue, but if you need my help to implement this feature in a separate bot that you want to create, you're welcome to ask for my assistance.

I'll start by directing you to the following attributes in `praw` that allow reading submission title and flair:

https://praw.readthedocs.io/en/stable/code_overview/models/submission.html?highlight=title
https://praw.readthedocs.io/en/stable/code_overview/models/submission.html?highlight=flair#praw.models.Submission.flair
