### ISSUE TITLE
Superscript text malformed on official Android app

### ISSUE THREAD

**Issue by henrebotha** [Toldry/RedditAutoCrosspostBot#3]
The bot message seems malformed on the official Android app. See screenshot. 

![Screenshot_20201219-185145_Reddit](https://user-images.githubusercontent.com/5593874/102695995-5b6f9b80-422b-11eb-97e5-5923cdae1353.jpg)

Is this how you want the "this comment was written by a bot" part to look? It looks like you're using superscript not quite correctly.

**Comment by Toldry** [comment]
Hey, thanks for reporting. 

I was already aware of this problem. From what I managed to gather, this seems to be a problem with the official Reddit android app, here's why:

When I post the exact same comment on the reddit android app, the text is rendered correctly:

![image](https://user-images.githubusercontent.com/7353619/102696643-7268ba80-4238-11eb-88f1-882d06022046.png)

Then, I left the thread, and re-entered it, after which the text became malformed:

![image](https://user-images.githubusercontent.com/7353619/102696653-801e4000-4238-11eb-8646-141f59d9022e.png)

Since the android app appears to be able to correctly render the comment when it is freshly-posted, it appears that the problem lies in the app's method of rendering text that was retrieved from the server (as opposed to rendring text that was input locally)

Also, the comment renders fine on the desktop web clients of reddit, both the old and new designs

Old design:
![image](https://user-images.githubusercontent.com/7353619/102696704-cf647080-4238-11eb-93f6-172354cb52de.png)

New design:
![image](https://user-images.githubusercontent.com/7353619/102696732-f622a700-4238-11eb-8558-6b9be8fc3577.png)


I'm closing this issue since there does not aappear to be a way to solve it, the reddit devs will need to fix what appears to be a bug in their android app.

**Comment by Toldry** [comment]
I just noticed that the text is slightly malformed in the new design screenshot; this appears to be another discrepancy in how different reddit clients render the same text, which I still consider to be a bug on their part.
