### ISSUE TITLE
Bot talks far too much in its comments

### ISSUE THREAD

**Issue by saxbophone** [Toldry/RedditAutoCrosspostBot#39]
Bot's comments are far too lengthy where it explains the reasons why it posted there and then. This is too much information for me to encounter when casually scrolling comments and I had this interaction the other day where I was so overburdened with information I didn't want when reading its comment that I stopped reading the rest of the thread.

- AS a Reddit User
  - WHEN I am scrolling through comments on a post
    - THEN I want to see comments from human users prioritised over those from bots
  - AND WHEN I do see a bot's comment
    - THEN I want the bot's comment to be very terse so I don't waste time reading information I value far lower than that of actual humans

![image](https://user-images.githubusercontent.com/8693463/225258361-606c30e2-d90d-40d8-abee-47c018ce808e.png)

[https://www.reddit.com/r/shittyskylines/comments/11pqvhi/comment/jbz9zpk/?utm_source=share&utm_medium=web2x&context=3](https://www.reddit.com/r/shittyskylines/comments/11pqvhi/comment/jbz9zpk/?utm_source=share&utm_medium=web2x&context=3)

**Comment by Toldry** [comment]
Hi Joshua, thanks for the feedback.

I agree with you that human-written comments are more valuable than bot-written comments. 

In order to make it obvious to users that this is an auto-generated comment, so users can quit reading it early if they want:
- The bot has username that starts with "Auto" and ends with "Bot"
- The bot has a profile picture of a robot
- The comment has a footer that specifies that the comment is written by a bot
- The comment is meticulously formatted in a way that ad-hoc human-written comment rarely are

I think the information provided by this auto generated comment is valuable, so I'm not interested in shortening it.

However, I am open to suggestions how to make it more early and obvious that the comment is auto-generated, so users such as yourself can choose to skip over it. I tried imitating design choices of other reddit bot designers. Do you have other suggestions I could implement?

**Comment by saxbophone** [comment]
> Hi Joshua, thanks for the feedback.

No problem, thanks for such a quick response

> I think the information provided by this auto generated comment is valuable, so I'm not interested in shortening it.
> 
> However, I am open to suggestions how to make it more early and obvious that the comment is auto-generated, so users such as yourself can choose to skip over it. I tried imitating design choices of other reddit bot designers. Do you have other suggestions I could implement?

I understand why you feel the need to keep the content explaining why the crossposts are made.

Tbh I feel like an ideal solution would be one where either the length explanation is minimised by default (a bit like how spoilers on some sites are rendered as a triangular arrow-button which you can click to expand them —unfortunately Reddit's spoilers are not formatted in this way and I don't know if there's any support for such constructs in the flavour of Markdown they support),

or, failing that, I feel like Reddit itself needs to provide users an option to display bot-posted comments as minimised by default. I know that's out of your area as it would be a feature within Reddit itself, but maybe we should provide them some feedback to that effect, since presumably Reddit is able to positively identify posts made by authorised bots.

**Comment by Toldry** [comment]
I would definitely add that arrow-button minimzation thing if it was an option.

Reddit definitely can positively identify posts authored by bots because bot accounts have a special registration process.

I suggest you contact Reddit directly with your feedback.

I think https://www.reddit.com/r/redesign/ is the default place for such suggestions.


I'm closing this issue since right now it is not actionable.


If you end up open a feedback thread on reddit, please link it here and I'll upvote your suggestion 😃

**Comment by saxbophone** [comment]
> I would definitely add that arrow-button minimzation thing if it was an option.
> 
> Reddit definitely can positively identify posts authored by bots because bot accounts have a special registration process.
> 
> I suggest you contact Reddit directly with your feedback.
> 
> I think https://www.reddit.com/r/redesign/ is the default place for such suggestions.
> 
> I'm closing this issue since right now it is not actionable.
> 
> If you end up open a feedback thread on reddit, please link it here and I'll upvote your suggestion 😃

Thanks, it's a good idea, cheers for signposting me there!

That subreddit is actually now archived, but they directed me to this one, where I've posted a Reddit version of what I originally requested here: https://www.reddit.com/r/ideasfortheadmins/comments/11rwxqa/i_would_like_reddit_to_give_users_the_option_to/
